spring.application.name=github

spring.ai.mcp.server.name=github-assistant
spring.ai.mcp.server.version=0.1.1

# mcp server config
spring.ai.mcp.server.protocol=streamable
spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.type=sync

github.token=${GITHUB_TOKEN}